version: "3.7"
services:

  app:
    build: .
    container_name: valorem-client-python
    volumes:
      - storage:/app/files
    env_file:
      - .env
    ports:
      - "8000:8000"

#  tsg-core-container:
#    image: docker.nexus.dataspac.es/core-container:feature-open-sourcing
#    pull_policy: always
#    volumes:
#      - ./application.yaml:/config/application.yaml:ro
#      - ./cachain.crt:/secrets/idsidentity/ca.crt:ro
#      - ./component.crt:/secrets/idsidentity/ids.crt:ro
#      - ./component.key:/secrets/idsidentity/ids.key:ro
#  tsg-admin-ui:
#    image: docker.nexus.dataspac.es/ui/core-container-ui:master
#    pull_policy: always
#    environment:
#      - API_BACKEND=tsg-core-container:8082/api/
#    ports:
#      - 31000:80

  # # Uncomment the block below to enable the OpenAPI data app
  # tsg-openapi-data-app:
  #   image: docker.nexus.dataspac.es/data-apps/openapi-data-app:feature-open-sourcing
  #   pull_policy: always
  #   volumes:
  #     - ./application.dataapp.yaml:/app/resources/application.yaml
  #   ports:
  #     - 31001:8080

volumes:
  storage:
