version: "3.7"
services:

  app:
    image: docker-registry.inesctec.pt/valorem/valorem-client-python/valorem-client-python-app
    container_name: valorem-client-python
    volumes:
      - storage:/app/files
    env_file:
      - .env

volumes:
  storage:
