version: "3.7"
services:

  app:
    build:
      context: .
      args:
      - GITLAB_TOKEN
    container_name: predico-rest-client-python
    env_file:
      - .env
    volumes:
      - storage:/app/files

    ports:
      - "8000:8000"

  db:
    image: postgres:12.0-alpine
    container_name: predico-client_postgresql
    restart: always
    environment:
      POSTGRES_DB: predico
      POSTGRES_USER: predico
      POSTGRES_PASSWORD: predico
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  storage:
  postgresql-data:


